const PAPER_ICON =
    "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='8' fill='%23d32f2f'/%3E%3Cpath d='M8 6h11l5 5v15H8z' fill='%23fff'/%3E%3Cpath d='M19 6v5h5' fill='none' stroke='%23d32f2f' stroke-width='1.5'/%3E%3Cpath d='M11 21.7h2.4c1.9 0 3-1 3-2.7s-1.1-2.6-3-2.6H11zm1.7-1.4v-2.5h0.8c0.9 0 1.4 0.4 1.4 1.2s-0.5 1.3-1.4 1.3zm5.5 1.4h1.6v-2.1h1.1c1.7 0 2.9-0.9 2.9-2.4s-1.1-2.5-2.9-2.5H18.2zm1.6-3.4v-2.1h0.9c0.8 0 1.2 0.4 1.2 1s-0.4 1.1-1.2 1.1z' fill='%23d32f2f'/%3E%3C/svg%3E";

window.linkCategories = [
    {
        id: "ai",
        title: "Künstliche Intelligenz",
        links: [
            { title: "Tiktokenizer", url: "https://tiktokenizer.vercel.app/" },
            { title: "BBYCROFT LLM", url: "https://bbycroft.net/llm" },
            { title: "LM Studio", url: "https://lmstudio.ai/" },
            { title: "Hyperbolic", url: "https://app.hyperbolic.xyz/" },
            { title: "Together Playground", url: "https://api.together.xyz/playground" },
            { title: "LMArena", url: "https://lmarena.ai/" },
            { title: "FineWeb Blogpost", url: "https://huggingface.co/spaces/HuggingFaceFW/blogpost-fineweb-v1" },
            { title: "The Llama 3 Herd of Models", url: "https://arxiv.org/abs/2407.21783" },
            { title: "InstructGPT Paper (SFT/RLHF)", url: "https://arxiv.org/abs/2203.02155" },
            { title: "DeepSeek-R1", url: "https://arxiv.org/abs/2501.12948" },
            { title: "AlphaGo", url: "https://discovery.ucl.ac.uk/id/eprint/10045895/1/agz_unformatted_nature.pdf" },
            { title: "Agent Skills by Addy Osmani", url: "https://github.com/addyosmani/agent-skills" },
            { title: "System Prompts Leaks", url: "https://github.com/asgeirtj/system_prompts_leaks" },
            { title: "AINews", url: "https://news.smol.ai/" },
        ],
    },
    {
        id: "news",
        title: "News",
        links: [
            { title: "Google News", url: "https://news.google.com/" },
            { title: "Spiegel Online", url: "https://www.spiegel.de/" },
            { title: "International", url: "https://www.spiegel.de/international/" },
            { title: "TheGuardian", url: "https://www.theguardian.com/international" },
            { title: "Handelsblatt", url: "https://www.handelsblatt.com/", icon: "https://resources.handelsblatt.com/hb-frontend/favicon.ico" },
            { title: "On Microsoft", url: "https://www.onmsft.com/", icon: "https://www.onmsft.com/wp-content/uploads/2021/03/cropped-Asset-1-192x192.png" },
            { title: "Windows Blogs", url: "https://blogs.windows.com/" },
            { title: "W10 Forum", url: "https://www.win-10-forum.de/" },
            { title: "Heise", url: "https://www.heise.de/" },
            { title: "finanz-szene", url: "https://www.finanz-szene.de/" },
            { title: "FAZ", url: "https://www.faz.net/" },
            { title: "RNZ", url: "https://www.rnz.de/" },
            { title: "Programming News", url: "https://gist.github.com/Phape/a60e09c4cfc5cf8caf31a900abda8ac6", icon: "https://github.githubassets.com/assets/pinned-octocat-093da3e6fa40.svg" },
        ],
    },
    {
        id: "entertainment",
        title: "Entertainment",
        links: [
            { title: "YouTube", url: "https://www.youtube.com/" },
            { title: "Netflix", url: "https://www.netflix.com/" },
            { title: "Prime Video", url: "https://www.amazon.de/Amazon-Video/b/ref=topnav_storetab_atv?node=3010075031&ie=UTF8" },
            { title: "Twitch", url: "https://www.twitch.tv/" },
            { title: "Reddit", url: "https://reddit.com/" },
            { title: "WhatsApp", url: "https://web.whatsapp.com/" },
            { title: "neal.fun", url: "https://neal.fun/" },
            { title: "classicReload", url: "https://classicreload.com/" },
            { title: "Reelgood", url: "https://reelgood.com/" },
            { title: "WerStreamt.es?", url: "https://www.werstreamt.es/" },
            { title: "Best similar", url: "https://bestsimilar.com/" },
        ],
    },
    {
        id: "shopping-finances",
        title: "Shopping & Finanzen",
        links: [
            { title: "mydealz", url: "https://www.mydealz.de/" },
            { title: "Amazon", url: "https://www.amazon.de/" },
            { title: "ebay", url: "https://www.ebay.de/" },
            { title: "Kleinanzeigen", url: "https://www.ebay-kleinanzeigen.de/" },
            { title: "N26", url: "https://app.n26.com/login" },
            { title: "VB-Kraichgau", url: "https://www.vbkraichgau.de/banking-private/entry", icon: "https://www.vbkraichgau.de/favicon.ico" },
            { title: "VB-Kraichgau", url: "https://www.vbkraichgau.de/services_cloud/portal/", icon: "https://www.vbkraichgau.de/favicon.ico?v2" },
            { title: "PayPal", url: "https://www.paypal.com/signin?country.x=DE&locale.x=de_DE" },
            { title: "LS Exchange", url: "https://www.ls-x.de/de/aktien-filter" },
            { title: "Der Aktionär", url: "https://www.deraktionaer.de/" },
        ],
    },
    {
        id: "dev-tools",
        title: "Dev & Tools",
        links: [
            { title: "GitHub", url: "https://github.com/" },
            { title: "Netcup CCP", url: "https://ccp.netcup.net/" },
            { title: "MS Dev", url: "https://developer.microsoft.com/de-de/windows" },
            { title: "Azure DevOps", url: "https://dev.azure.com/phape/" },
            { title: "Host Unlimited", url: "https://c-area.host-unlimited.de/" },
            { title: "CodeSandbox", url: "https://codesandbox.io/" },
            { title: "TLD Verfügbarkeit", url: "https://instantdomainsearch.com/", icon: "https://instantdomainsearch.com/favicon.svg?v=PYq02Qy8dr" },
            { title: "PDF-Tools", url: "https://png2pdf.com/" },
            { title: "PDF Cropper", url: "https://www.sejda.com/crop-pdf" },
            { title: "PDF drehen", url: "https://smallpdf.com/de/pdf-drehen" },
            { title: "WayBack Machine", url: "https://web.archive.org/" },
            { title: "draw.io", url: "https://www.draw.io/" },
            { title: "Excalidraw", url: "https://excalidraw.com/" },
            { title: "Abfallkalender", url: "https://mankei.eu/abfallkalender/profile.php?id=amzn1.ask.account.AGW4BGVF3AX6QP6MHRD6AS4BSCJ5HCNC4G2VHYVYYGXRPUHLDJZ3EAITPWM2CVEEZOXPHMGLQMX76LIJTREREBJPXSCKFIAEQZQREZA32M7RUUDCAGMURYBODJBAJUWE5CTRPMFPSEP4OGOCSGKGGIVHD5JJOLK6YTTY7MHB7L4GSX3TDC6MYMDR3XELLOPYL6WEAGSQPHXCJII" },
            { title: "Statista", url: "https://de.statista.com/" },
            { title: "Temp Mail", url: "https://temp-mail.org/" },
            { title: "Photopea", url: "https://www.photopea.com/" },
        ],
    },
    {
        id: "work-uni",
        title: "Arbeit & Uni",
        links: [
            { title: "Cofinpro Portal", url: "https://webapps.cofinpro.com/" },
            { title: "Cofinpro Wiki", url: "http://studi-wiki.cofinpro.de/" },
            { title: "DHBW Moodle", url: "https://moodle.dhbw.de/my/" },
            { title: "DHBW RaPla", url: "https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=wengler&file=wwi18B4" },
            { title: "Duolingo", url: "https://www.duolingo.com/" },
        ],
    },
    {
        id: "music",
        title: "Musik",
        links: [
            { title: "Spotify", url: "https://open.spotify.com" },
            { title: "Noiiz", url: "https://www.noiiz.com/" },
            { title: "WhoSampled", url: "https://www.whosampled.com/" },
            { title: "Spotify sort", url: "http://sortyourmusic.playlistmachinery.com/index.html" },
            { title: "Spotify organizer", url: "http://organizeyourmusic.playlistmachinery.com/" },
            { title: "SpotifyTools", url: "https://spotifytools.phape.de" },
        ],
    },
];